# Copyright Amazon.com, Inc. or its affiliates. All Rights Reserved.
# SPDX-License-Identifier: MIT-0
AWSTemplateFormatVersion: 2010-09-09

Parameters:
  SubnetId:
    Type: "String"
  ClusterName:
    Type: "String"
    Default: "One Node Cluster"
  EmrRelease:
    Type: "String"
    Default: "emr-6.9.0"
    AllowedValues:
    - "emr-6.9.0"
    - "emr-5.33.1"
  ClusterInstanceType:
    Type: "String"
    Default: "m5.xlarge"
    AllowedValues:
    - "m5.xlarge"
    - "r6gd.xlarge"
  MasterInstanceType:
    Type: "String"
    Default: "m5.xlarge"
    AllowedValues:
    - "r5.xlarge"
    - "m5.xlarge"

Resources:
  EmrCluster:
    Type: AWS::EMR::Cluster
    Properties:
      Applications:
      - Name: Spark
      - Name: Livy
      - Name: JupyterEnterpriseGateway
      - Name: Hive
      - Name: Hue
      - Name: Presto
      BootstrapActions:
      - Name: Instrument-Model-Dependencies
        ScriptBootstrapAction:
          Path: 's3://fb-dev-edw-artifacts-needles-io-ap-southeast-2/configs/instrument_model_bootstrap.sh'
      EbsRootVolumeSize: '100'
      Name: !Ref ClusterName
      JobFlowRole: EMR_EC2_DefaultRole
      ServiceRole: EMR_DefaultRole
      ReleaseLabel: !Ref EmrRelease
      VisibleToAllUsers: true
      LogUri: 's3://fb-dev-athena-datalake-needles-io-ap-southeast-2/emr_logs/'
      Instances:
        TerminationProtected: false
        Ec2SubnetId: !Ref SubnetId
        MasterInstanceGroup:
          InstanceCount: 1
          InstanceType: !Ref MasterInstanceType
        CoreInstanceGroup:
          InstanceCount: 1
          InstanceType: !Ref ClusterInstanceType
          Market: ON_DEMAND
          Name: Core
        Ec2KeyName: 'elora'

      Configurations:
      - Classification: spark-hive-site
        ConfigurationProperties:
          hive.metastore.client.factory.class: com.amazonaws.glue.catalog.metastore.AWSGlueDataCatalogHiveClientFactory
          hive.metastore.schema.verification: false
      - Classification: presto-connector-hive
        ConfigurationProperties:
          hive.metastore: glue
      - Classification: delta-defaults
        ConfigurationProperties:
          delta.enabled: true

