# Copyright Amazon.com, Inc. or its affiliates. All Rights Reserved.
# SPDX-License-Identifier: MIT-0
AWSTemplateFormatVersion: 2010-09-09

Parameters:
  SubnetId:
    Type: "String"
  ClusterName:
    Type: "String"
    Default: "Twenty Node Cluster"
  EmrRelease:
    Type: "String"
    Default: "emr-6.8.0"
    AllowedValues:
    - "emr-6.8.0"
    - "emr-5.33.1"
Resources:
  EmrCluster:
    Type: AWS::EMR::Cluster
    Properties:
      Applications:
      - Name: Spark
      - Name: Livy
      - Name: JupyterEnterpriseGateway
      - Name: Hive
      - Name: Hue
      - Name: Presto
      BootstrapActions:
      - Name: Instrument-Model-Dependencies
        ScriptBootstrapAction:
          Path: 's3://fb-dev-edw-artifacts-needles-io-ap-southeast-2/configs/instrument_model_bootstrap.sh'
      EbsRootVolumeSize: '50'
      Name: !Ref ClusterName
      JobFlowRole: EMR_EC2_DefaultRole
      ServiceRole: EMR_DefaultRole
      ReleaseLabel: !Ref EmrRelease
      VisibleToAllUsers: true
      LogUri: 's3://fb-dev-athena-datalake-needles-io-ap-southeast-2/emr_logs/'
      Instances:
        TerminationProtected: False
        CoreInstanceFleet:
          InstanceTypeConfigs:
            - InstanceType: m6gd.xlarge
              WeightedCapacity: 1
            - InstanceType: m6gd.2xlarge
              WeightedCapacity: 1
          Name:
            Ref: AWS::StackName
          TargetOnDemandCapacity: "2"
          LaunchSpecifications:
            OnDemandSpecification:
              AllocationStrategy: lowest-price
        Ec2SubnetId: !Ref SubnetId
        MasterInstanceFleet:
          InstanceTypeConfigs:
            - InstanceType: c4.large
            - InstanceType: m4.large
          Name:
            Ref: AWS::StackName
          TargetOnDemandCapacity: "1"
      Configurations:
      - Classification: spark-hive-site
        ConfigurationProperties:
          hive.metastore.client.factory.class: com.amazonaws.glue.catalog.metastore.AWSGlueDataCatalogHiveClientFactory
          hive.metastore.schema.verification: false
      - Classification: presto-connector-hive
        ConfigurationProperties:
          hive.metastore: glue
      - Classification: spark-env
        ConfigurationProperties:
          hive.metastore: glue
  TaskInstanceFleet:
    Type: AWS::EMR::InstanceFleetConfig
    Properties:
      ClusterId:
        Ref: EmrCluster
      InstanceFleetType: TASK
      InstanceTypeConfigs:
        - InstanceType: m5.2xlarge
          WeightedCapacity: 2
        - InstanceType: m5a.2xlarge
          WeightedCapacity: 2
        - InstanceType: m5.xlarge
          WeightedCapacity: 1
      LaunchSpecifications:
        SpotSpecification:
          TimeoutAction: TERMINATE_CLUSTER
          TimeoutDurationMinutes: 80
          AllocationStrategy: capacity-optimized
      Name: TaskFleet
      TargetSpotCapacity: "16"

Outputs:
  ClusterId:
    Value: 
      Ref: EmrCluster
    Description: The ID of the EMR Cluster


